version: "2"
services:
   
    

    web:
        build: .
        command: python -u final.py
        ports: 
            - "5000:5000"
        volumes:
            - .:/mongo
        depends_on: 
            - db
    
        restart: always
    
    db:
            image: kourlosdimitris/mongodb
            restart: always
            ports:
             - 27017:27017
            volumes:
                - ./data:/data/db
